name: Yeni Metin Belgesi
favicon: null
layout_spectrum: 0.17154334345832467
typography_spectrum: 0.4277446218766272
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6486788622569293
  lightness: 0.281862877542153
  saturation: 0.45892689167521894
  rhythmicContrast: 0.968035050900653
purpose: []
